/**
 * Email content sections for demo signup emails
 * Extracted as constants for easier content editing and maintenance
 */
const EMAIL_CONTENT = {
  HEADER: 'Welcome to PipeTrak!',
  WELCOME_MESSAGE: `Thanks for trying PipeTrak! We're the industrial pipe tracking system designed
    for brownfield construction projects. Track component progress, manage milestones,
    and keep your entire team in sync.`,
  CTA_TEXT: 'Access Your Demo Project →',
  QUICK_START_TITLE: 'What to Explore First:',
  QUICK_START_ITEMS: [
    { title: 'Progress Dashboard', description: 'See your 200 sample components with milestone tracking' },
    { title: 'Drawing Table', description: 'Explore the 20 test drawings with component assignments' },
    { title: 'Test Packages', description: 'Review the 10 pre-configured test packages' },
    { title: 'Team Management', description: 'Try inviting team members to collaborate' }
  ],
  SUPPORT_LINK: 'https://pipetrak.co'
} as const

/**
 * Email styling constants
 * Inline styles required for email client compatibility
 */
const EMAIL_STYLES = {
  BODY: 'font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;',
  HEADER: 'color: #2563eb;',
  CTA_BUTTON: 'background: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;',
  CTA_CONTAINER: 'margin: 30px 0;',
  SECTION_TITLE: 'color: #1e40af; font-size: 18px;',
  FOOTER_TEXT: 'color: #6b7280; font-size: 14px; margin-top: 40px;',
  EXPIRY_TEXT: 'color: #6b7280; font-size: 14px; margin-top: 20px;'
} as const

/**
 * Generate custom HTML email template for demo signup
 *
 * This function creates a branded email sent via Resend API when a user signs up
 * for a demo project. The email includes:
 * - Personalized welcome message with user's name
 * - Magic link button for authentication (generated by Supabase Auth)
 * - Quick start guide with 4 suggested features to explore
 * - Demo expiration date (7 days from signup)
 * - Footer with support contact and website link
 *
 * Email uses inline styles for maximum compatibility with email clients.
 * Template variables are safely interpolated (no HTML escaping needed for fullName
 * as email clients handle this, and magicLinkUrl is URL-safe from Supabase).
 *
 * @param fullName - User's full name from signup form (e.g., "John Smith")
 * @param magicLinkUrl - Supabase magic link URL for one-click authentication
 * @param demoExpiresAt - ISO 8601 timestamp of demo expiration (e.g., "2025-11-05T10:00:00.000Z")
 * @returns Complete HTML email string ready to send via Resend API
 *
 * @example
 * ```typescript
 * const html = generateDemoEmailHtml(
 *   'Jane Doe',
 *   'https://example.supabase.co/auth/v1/verify?token=abc123',
 *   '2025-11-05T10:00:00.000Z'
 * )
 * // Returns: "<!DOCTYPE html>..."
 * ```
 */
export function generateDemoEmailHtml(
  fullName: string,
  magicLinkUrl: string,
  demoExpiresAt: string
): string {
  // Format expiry date as "Month Day, Year" (e.g., "November 5, 2025")
  // Use UTC timezone to avoid conversion issues with ISO timestamps
  const expiryDate = new Date(demoExpiresAt).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC'
  })

  // Generate quick start guide list items
  const quickStartItems = EMAIL_CONTENT.QUICK_START_ITEMS
    .map(item => `<li><strong>${item.title}</strong> - ${item.description}</li>`)
    .join('\n    ')

  return `
<!DOCTYPE html>
<html>
<body style="${EMAIL_STYLES.BODY}">

  <!-- Header -->
  <h1 style="${EMAIL_STYLES.HEADER}">${EMAIL_CONTENT.HEADER}</h1>

  <!-- Welcome message with brand intro -->
  <p>Hi ${fullName},</p>
  <p>
    ${EMAIL_CONTENT.WELCOME_MESSAGE}
  </p>

  <!-- Magic link CTA -->
  <div style="${EMAIL_STYLES.CTA_CONTAINER}">
    <a href="${magicLinkUrl}"
       style="${EMAIL_STYLES.CTA_BUTTON}">
      ${EMAIL_CONTENT.CTA_TEXT}
    </a>
  </div>

  <!-- Quick start guide -->
  <h2 style="${EMAIL_STYLES.SECTION_TITLE}">${EMAIL_CONTENT.QUICK_START_TITLE}</h2>
  <ul>
    ${quickStartItems}
  </ul>

  <p style="${EMAIL_STYLES.EXPIRY_TEXT}">
    Your demo access is valid until ${expiryDate}.
  </p>

  <!-- Footer -->
  <p style="${EMAIL_STYLES.FOOTER_TEXT}">
    Questions? Reply to this email or visit
    <a href="${EMAIL_CONTENT.SUPPORT_LINK}">pipetrak.co</a>
  </p>

</body>
</html>
  `.trim()
}
