-- Add unique constraints needed for demo skeleton creation idempotency
-- Feature: 023-demo-data-population

-- Areas: unique (project_id, name)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'areas_project_id_name_key'
  ) THEN
    ALTER TABLE areas ADD CONSTRAINT areas_project_id_name_key UNIQUE (project_id, name);
  END IF;
END $$;

-- Systems: unique (project_id, name)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'systems_project_id_name_key'
  ) THEN
    ALTER TABLE systems ADD CONSTRAINT systems_project_id_name_key UNIQUE (project_id, name);
  END IF;
END $$;

-- Test Packages: unique (project_id, name)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'test_packages_project_id_name_key'
  ) THEN
    ALTER TABLE test_packages ADD CONSTRAINT test_packages_project_id_name_key UNIQUE (project_id, name);
  END IF;
END $$;

-- Welders: unique (project_id, stencil_norm)
-- Note: stencil_norm is auto-generated by trigger from stencil
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'welders_project_id_stencil_norm_key'
  ) THEN
    ALTER TABLE welders ADD CONSTRAINT welders_project_id_stencil_norm_key UNIQUE (project_id, stencil_norm);
  END IF;
END $$;

COMMENT ON CONSTRAINT areas_project_id_name_key ON areas IS 'Ensures area names are unique within a project (required for demo skeleton idempotency)';
COMMENT ON CONSTRAINT systems_project_id_name_key ON systems IS 'Ensures system names are unique within a project (required for demo skeleton idempotency)';
COMMENT ON CONSTRAINT test_packages_project_id_name_key ON test_packages IS 'Ensures test package names are unique within a project (required for demo skeleton idempotency)';
COMMENT ON CONSTRAINT welders_project_id_stencil_norm_key ON welders IS 'Ensures welder stencils are unique within a project (required for demo skeleton idempotency)';
